export let stories = [
    {id:"1",message: "You and your grandma is out taking a walk in the forest.", img:"https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/silhouettes-of-two-people-walking-away-down-forest-path-cavan-images.jpg",choices:[{id:"2",text:"Begin"}]},
    {id:"2",message: "After walking for a little bit the path splits, wich way will you choose?", img:"https://billmunncoaching.com/wp-content/uploads/2014/06/split-path-representing-the-multiple-routes-we-can-take-to-success.jpg",choices:[{id:"3",text:"Left"},{id:"4",text:"Right"},{id:"16",text:"Through the dense part of the forest"}]},
    {id:"3",message: "You take the left path. The forest gradually grows darker and you can't help but get a feeling that you are being watched. Suddenly you hear a sound comming from behind you, what do you do?", img:"https://wallpapercrafter.com/th800/163702-silhouette-artwork-forest-night-horror-Yeti-creepy-dark-fictional-creatures-creature-deep-forest-spooky-frontal-view.jpg",choices:[{id:"5",text:"Look behind you."},{id:"9",text:"Run. Everyman for themselves"}]},
    {id:"4",message: "You walk the right path. The path is calm and tranquil and you have a good time talking to your grandma. When a bear suddenly jumps out in front of you!", img:"https://files.worldwildlife.org/wwfcmsprod/images/Brown_Bear_/story_full_width/3box0qwlkk_brownbear_hero.jpg",choices:[{id:"7",text:"Fight the bear"},{id:"10",text:"Throw grandma to the bear."}]},
    {id:"5",message: "Behind you to your horror you see a big bad bear! What do you do now?", img:"https://www.collinsdictionary.com/images/full/brownbear_259894163.jpg",choices:[{id:"6",text:"Fight the bear"},{id:"10",text:"Push your grandma and run away"}]},
    {id:"6",message: "The bear goes in for attack, what do you do?", img:"https://www.cnet.com/a/img/resize/79c6633a7eec60f47f847e964226a058324f88ca/hub/2015/08/28/ed717fd4-ae69-48b9-bef8-d06a30718b3d/grizzly-bear.jpg?auto=webp&fit=crop&height=675&width=1200",choices:[{id:"7",text:"Tackle the bear."},{id:"8",text:"Dodge it's attack and counter attack."}]},
    {id:"7",message: "You are mauled to death by the bear.", html: '<div style="width:480px"><iframe allow="fullscreen" frameBorder="0" height="360" src="https://thumbs.gfycat.com/SafeBlaringAmericanquarterhorse-size_restricted.gif" width="480"></iframe></div>',choices:[{id:"1",text:"Start over?"}]},
    {id:"8",message: "You dodge the bear! What now?", html:'<div style="width:480px"><iframe allow="fullscreen" frameBorder="0" height="360" src="https://i.pinimg.com/originals/f9/ed/a8/f9eda8f91763ba8b2def51a79bf5343e.gif" width="480"></iframe></div>',choices:[{id:"7",text:"Wrestle the bear."},{id:"10",text:"Realising your mistake and you give grandma to the big bad bear and run away."}]},
    {id:"9",message: "You trip and hit your head on a rock and die.", html: '<div style="width:480px"><iframe allow="fullscreen" frameBorder="0" height="360" src="https://media.tenor.com/tKLtM4Ym7YoAAAAC/tim-bernardes-o-terno.gif" width="480"></iframe></div>',choices:[{id:"1",text:"Start Over?"}]},   
    {id:"10",message: "You throw grandma at the bear, you hear her old lady scream echo through the forest as you run away from the bear.", img:"https://media.istockphoto.com/id/183114652/photo/neurotic-grandma.jpg?s=170667a&w=0&k=20&c=ioFH6gOAMgeS_d7aQSjfLHB1KatP24Eor0_CC8yuZPQ=",choices:[{id:"7",text:"Go back for grandma?"},{id:"11",text:"Continue running"}]},
    {id:"11",message: "The screams still echo through the forest when they suddenly stop. ", img:"https://media.gettyimages.com/id/104566865/photo/businessman-running-looking-over-shoulder.jpg?s=612x612&w=gi&k=20&c=eThVjlLFLoLMA0FZROT2kxJXUTf_w4iQkUUZvtQp3xw= ",choices:[{id:"7",text:"Go back to see what happened?"},{id:"15",text:"Continue forward."}]},
    {id:"12",message: "You can see the end of the forest. ", img:"https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/light-at-the-end-of-the-forest-dawn-van-doorn.jpg",choices:[{id:"2",text:"Take another stroll through the forest?"},{id:"13",text:"Run towards the end of the forest?"}]},
    {id:"13",message: "You make it out of the forest, you feel refreshed and happy.", html: '<div style="width:480px"><iframe allow="fullscreen" frameBorder="0" height="360" src="https://steamuserimages-a.akamaihd.net/ugc/940581010213045659/7F123BDEAF366C1E3DCC3925C801ABA7E5E4CB5C/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true" width="480"></iframe></div>',choices:[{id:"1",text:"Reset!"}]},
    {id:"14",message: "You make it out of the forest, you feel dreadful.", img:"https://bahaiteachings.s3.us-west-1.amazonaws.com/2017/11/That-Spreading-Sense-Dread-We-Feel.jpg",choices:[{id:"1",text:"Reset!"}]},
    {id:"15",message: "You can see the end of the forest. ", img:"https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/light-at-the-end-of-the-forest-dawn-van-doorn.jpg",choices:[{id:"7",text:"Take another stroll through the forest?"},{id:"14",text:"Run towards the end of the forest?"}]},
    {id:"16",message: "The forest is hard to walk trough.", img:"https://www.mountainphotography.com/images/xl/20081029-Fox-Glacier-Forest.jpg",choices:[{id:"17",text:"Go back to the path?"},{id:"12",text:"Continue forward!"}]},
    {id:"17",message: "You are back at where the path splits.", img:"https://billmunncoaching.com/wp-content/uploads/2014/06/split-path-representing-the-multiple-routes-we-can-take-to-success.jpg",choices:[{id:"3",text:"Left"},{id:"4",text:"Right"}]} 
]